stages:
  discover:
    cmd: tladata discover
    deps:
      - config/seeds/repos.yaml
      - config/seeds/queries.yaml
      - src/tladata/discovery
    outs:
      - manifests/sources/sources_latest.jsonl
      - manifests/sources/sources_latest_formatted.jsonl

  pull:
    cmd: tladata pull
    deps:
      - manifests/sources/sources_latest.jsonl
      - src/tladata/extraction
    outs:
      - data/raw

  push-to-s3:
    cmd: tladata push-to-s3 --bucket luc-tla-datasets --prefix raw --manifest-prefix manifests/sources
    deps:
      - data/raw
      - manifests/sources/sources_latest.jsonl
      - manifests/sources/sources_latest_formatted.jsonl

  generate-extraction-manifest:
    cmd: tladata generate-manifest --input data/raw --output manifests/extraction/extraction_manifest.jsonl
    deps:
      - data/raw
      - src/tladata/discovery
    outs:
      - manifests/extraction/extraction_manifest.jsonl

  transform:
    cmd: tladata transform --extraction-manifest manifests/extraction/extraction_manifest.jsonl --extracted-files-root data/raw --output-fine data/processed/tla-components-fine.json --output-coarse data/processed/tla-components-coarse.json --output-individual-dir data/processed/json
    deps:
      - data/raw
      - manifests/extraction/extraction_manifest.jsonl
      - src/tladata/transform
    outs:
      - data/processed/tla-components-fine.json
      - data/processed/tla-components-coarse.json
      - data/processed/json
